#!/usr/bin/env python3
"""
Test Coverage Expansion Helper.

Helps identify files needing tests and generates test templates.

Usage:
    python scripts/expand_test_coverage.py --analyze --output test_plan.json
    python scripts/expand_test_coverage.py --generate --target model_based_rl
"""

import json
import argparse
import subprocess
import sys
from pathlib import Path
from typing import List, Dict, Any

# Project root
PROJECT_ROOT = Path(__file__).parent.parent


def analyze_coverage_gaps(threshold: float = 95.0) -> List[Dict[str, Any]]:
    """Analyze coverage gaps and identify priority files."""
    try:
        # Run coverage analysis
        result = subprocess.run(
            ["pytest", "--cov=src", "--cov-report=json", "--quiet"],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT
        )
        
        coverage_file = PROJECT_ROOT / "coverage.json"
        if not coverage_file.exists():
            print("Error: coverage.json not found. Run pytest with --cov-report=json first.", file=sys.stderr)
            return []
        
        with open(coverage_file) as f:
            data = json.load(f)
        
        gaps = []
        
        for file_path, file_data in data.get("files", {}).items():
            # Skip test files
            if "test" in file_path.lower() or "__pycache__" in file_path:
                continue
            
            summary = file_data.get("summary", {})
            coverage = summary.get("percent_covered", 0.0)
            
            if coverage < threshold:
                # Determine priority based on file location and coverage gap
                priority = "high"
                if "research" in file_path or "experimental" in file_path:
                    priority = "low"
                elif "utils" in file_path or "config" in file_path:
                    priority = "medium"
                elif "rl" in file_path or "control" in file_path:
                    priority = "high"
                
                gaps.append({
                    "file": file_path,
                    "coverage": coverage,
                    "gap": threshold - coverage,
                    "priority": priority,
                    "statements": summary.get("num_statements", 0),
                    "missing": summary.get("missing_lines", 0)
                })
        
        # Sort by priority and gap
        gaps.sort(key=lambda x: (
            {"high": 0, "medium": 1, "low": 2}[x["priority"]],
            -x["gap"]
        ))
        
        return gaps
    
    except Exception as e:
        print(f"Error analyzing coverage: {e}", file=sys.stderr)
        return []


def identify_critical_paths() -> List[str]:
    """Identify critical path files that need tests."""
    critical_files = [
        "src/research/novel_algorithms/model_based_rl.py",
        "src/research/novel_algorithms/hierarchical_rl.py",
        "src/research/novel_algorithms/transformer_control.py",
        "src/rl/dqn_agent.py",
        "src/env/traffic_env.py",
    ]
    
    # Check which exist
    existing = [f for f in critical_files if (PROJECT_ROOT / f).exists()]
    
    return existing


def generate_test_template(file_path: str, class_name: str = None) -> str:
    """Generate a test template for a file."""
    template = f'''"""
Tests for {file_path}

Generated by expand_test_coverage.py
"""

import pytest
import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from {file_path.replace('/', '.').replace('.py', '')} import {class_name or 'YourClass'}


class Test{''.join(word.capitalize() for word in (class_name or 'YourClass').split('_'))}:
    """Test suite for {class_name or 'YourClass'}."""
    
    def test_initialization(self):
        """Test object initialization."""
        # TODO: Implement test
        pass
    
    def test_basic_functionality(self):
        """Test basic functionality."""
        # TODO: Implement test
        pass
    
    def test_edge_cases(self):
        """Test edge cases."""
        # TODO: Implement test
        pass
'''
    
    return template


def main():
    parser = argparse.ArgumentParser(description="Expand test coverage")
    parser.add_argument("--analyze", action="store_true", help="Analyze coverage gaps")
    parser.add_argument("--generate", action="store_true", help="Generate test templates")
    parser.add_argument("--target", type=str, help="Target file or class to generate tests for")
    parser.add_argument("--threshold", type=float, default=95.0, help="Coverage threshold")
    parser.add_argument("--output", type=Path, help="Output file path")
    
    args = parser.parse_args()
    
    if args.analyze:
        gaps = analyze_coverage_gaps(args.threshold)
        critical = identify_critical_paths()
        
        report = {
            "coverage_gaps": gaps,
            "critical_paths": critical,
            "summary": {
                "total_gaps": len(gaps),
                "high_priority": sum(1 for g in gaps if g["priority"] == "high"),
                "medium_priority": sum(1 for g in gaps if g["priority"] == "medium"),
                "low_priority": sum(1 for g in gaps if g["priority"] == "low")
            }
        }
        
        if args.output:
            with open(args.output, 'w') as f:
                json.dump(report, f, indent=2)
            print(f"Coverage analysis saved to {args.output}")
        else:
            print("\n📊 Coverage Gap Analysis")
            print("=" * 80)
            print(f"Total files below {args.threshold}%: {len(gaps)}")
            print(f"High priority: {report['summary']['high_priority']}")
            print(f"Medium priority: {report['summary']['medium_priority']}")
            print(f"Low priority: {report['summary']['low_priority']}")
            print("\nTop 20 priority files:")
            print("-" * 80)
            for i, gap in enumerate(gaps[:20], 1):
                priority_icon = "🔴" if gap["priority"] == "high" else "🟡" if gap["priority"] == "medium" else "🟢"
                print(f"{i:2d}. {priority_icon} {gap['file']} ({gap['coverage']:.1f}%, gap: {gap['gap']:.1f}%)")
    
    elif args.generate:
        if not args.target:
            print("Error: --target required for --generate", file=sys.stderr)
            sys.exit(1)
        
        # Generate test template
        template = generate_test_template(args.target)
        
        if args.output:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            with open(args.output, 'w') as f:
                f.write(template)
            print(f"Test template saved to {args.output}")
        else:
            print(template)
    
    else:
        parser.print_help()


if __name__ == "__main__":
    main()

